const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log("🔧 PR Reviewer Core Package Build Fix");
console.log("====================================");

// Clean previous build
if (fs.existsSync(path.join(__dirname, 'dist'))) {
  console.log("\n🧹 Cleaning previous build...");
  fs.rmSync(path.join(__dirname, 'dist'), { recursive: true, force: true });
}

// Step 1: Build JavaScript files with esbuild directly (bypassing tsup)
console.log("\n📦 Building JavaScript files with esbuild...");
try {
  // Create dist directory
  fs.mkdirSync(path.join(__dirname, 'dist'), { recursive: true });
  
  // Build commonjs version
  execSync('npx esbuild src/index.ts --bundle --platform=node --target=node14 --format=cjs --outfile=dist/index.js', 
    { stdio: 'inherit' }
  );
  
  // Build ESM version
  execSync('npx esbuild src/index.ts --bundle --platform=node --target=node14 --format=esm --outfile=dist/index.mjs',
    { stdio: 'inherit' }
  );
  
  console.log("✅ JavaScript build successful!");
} catch (error) {
  console.error("❌ JavaScript build failed:", error.message);
  process.exit(1);
}

// Step 2: Generate a simple type declaration file
console.log("\n📝 Creating a simple type declaration file...");
try {
  const declarationContent = `/**
 * PR Reviewer Core Package
 * Generated by build-fix.js
 */

// VCS Client Types
export interface VCSClient {
  getPlatform(): string;
  getCurrentUser(): Promise<any>;
  getRepository(owner: string, name: string): Promise<any>;
  listUserRepositories(params?: any): Promise<any>;
  listOrganizationRepositories(org: string, params?: any): Promise<any>;
  getPullRequest(owner: string, repo: string, number: number): Promise<any>;
  listPullRequests(owner: string, repo: string, params?: any): Promise<any>;
  getPullRequestFiles(owner: string, repo: string, number: number): Promise<any[]>;
  getPullRequestCommits(owner: string, repo: string, number: number): Promise<any[]>;
  getPullRequestReviews(owner: string, repo: string, number: number): Promise<any[]>;
  getPullRequestComments(owner: string, repo: string, number: number): Promise<any[]>;
  getRateLimit(): Promise<any>;
}

// Error Classes
export class VCSError extends Error {
  constructor(message: string, platform: string, code: string, details?: any) {
    super(message);
  }
}

export class RepositoryError extends Error {
  constructor(message: string, details?: any) {
    super(message);
  }
}

export class AnalysisLimitError extends Error {
  current: number;
  limit: number;
  
  constructor(message: string, current: number, limit: number) {
    super(message);
    this.current = current;
    this.limit = limit;
  }
}

// Export factory function
export function createVCSClient(platform: string, token: string, options?: any): VCSClient;

// Repository Service
export class RepositoryService {
  constructor(dbService: any, tokens?: any);
  getRepository(platform: string, owner: string, name: string): Promise<any>;
  incrementAnalysisCount(platform: string, owner: string, repo: string, bypassLimit?: boolean): Promise<number>;
  checkRepositoryAccess(platform: string, owner: string, repo: string): Promise<any>;
}

// Database Service
export class DatabaseService {
  constructor(supabase: any);
  getRepository(fingerprint: string): Promise<any>;
  createRepository(data: any): Promise<any>;
  updateRepository(id: string, data: any): Promise<any>;
  incrementAnalysisCount(id: string): Promise<number>;
}

// Utils
export function createRepositoryFingerprint(platform: string, owner: string, repo: string): string;
`;
  
  fs.writeFileSync(path.join(__dirname, 'dist', 'index.d.ts'), declarationContent);
  fs.writeFileSync(path.join(__dirname, 'dist', 'index.d.mts'), declarationContent);
  
  console.log("✅ Type declarations created!");
} catch (error) {
  console.error("❌ Failed to create type declarations:", error.message);
  process.exit(1);
}

console.log("\n🎉 Build fix completed! The core package should now work properly.");
