name: Build and Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm globally
        run: pnpm install --no-frozen-lockfile
      - name: Verify pnpm installation
        run: pnpm --version
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build